### SERVER
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

### SPRING
spring:
  application:
    name: voting-session-manager-service
  output:
    ansi:
      enabled: ALWAYS

### APPLICATION
app:
  session:
    time: 5

### LOGGING
logging:
  level:
    root: INFO
    com:
      example: TRACE

### ACTUATOR
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  info:
    env:
      enabled: true

### INFORMATION
info:
  app:
    name: "voting-session-manager-service"
    description: "Voting session manager service"
  author: "Leonardo Ohashi"
  java-version: ${java.version}
