### SERVER
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

### SPRING
spring:
  application:
    name: voting-session-manager-service
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: ${MONGO_DB_URL:mongodb://root:toor@localhost:27017/admin}

### APPLICATION
app:
  session:
    time: ${SESSION_TIME_SECONDS:60}

### LOGGING
logging:
  level:
    root: INFO
    com:
      example: TRACE

### ACTUATOR
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  info:
    env:
      enabled: true

### INFORMATION
info:
  app:
    name: "voting-session-manager-service"
    description: "Voting session manager service"
  author: "Leonardo Ohashi"
  java-version: ${java.version}
